routes/web.php
<?php

use App\Category;
use App\Http\Controllers\CommentController;
use App\Mail\NewPost;
use App\Post;
use App\Tag;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes(['verify' => true]);

// Social Login
Route::get('login/google', 'Auth\LoginController@redirectToProvider');
Route::get('login/google/callback', 'Auth\LoginController@handleProviderCallback');



Route::get('/', 'HomeController@index')->name('home');
Route::get('/posts', 'HomeController@posts')->name('posts');
Route::get('/post/{slug}', 'HomeController@post')->name('post');
Route::get('/categories', 'HomeController@categories')->name('categories');
Route::get('/category/{slug}', 'HomeController@categoryPost')->name('category.post');
Route::get('/search', 'HomeController@search')->name('search');
Route::get('/tag/{name}', 'HomeController@tagPosts')->name('tag.posts');
Route::post('/comment/{post}', 'CommentController@store')->name('comment.store')->middleware(['auth', 'verified']);
Route::post('/comment-reply/{comment}', 'CommentReplyController@store')->name('reply.store')->middleware(['auth', 'verified']);
Route::post('/like-post/{post}', 'HomeController@likePost')->name('post.like')->middleware(['auth', 'verified']);


// Admin ////////////////////////////////////////////////////////////////////////
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth', 'admin','verified']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('profile', 'DashboardController@showProfile')->name('profile');
    Route::put('profile', 'DashboardController@updateProfile')->name('profile.update');
    Route::put('profile/password', 'DashboardController@changePassword')->name('profile.password');
    Route::resource('user', 'UserController')->except(['create', 'show', 'edit', 'store']);
    Route::resource('category', 'CategoryController')->except(['create', 'show', 'edit']);
    Route::resource('post', 'PostController');
    Route::get('/comments', 'CommentController@index')->name('comment.index');
    Route::delete('/comment/{id}', 'CommentController@destroy')->name('comment.destroy');
    Route::get('/reply-comments', 'CommentReplyController@index')->name('reply-comment.index');
    Route::delete('/reply-comment/{id}', 'CommentReplyController@destroy')->name('reply-comment.destroy');
    Route::get('/post-liked-users/{post}', 'PostController@likedUsers')->name('post.like.users');

});

// User ////////////////////////////////////////////////////////////////////////
Route::group(['prefix' => 'user', 'as' => 'user.', 'namespace' => 'User', 'middleware' => ['auth', 'user', 'verified']], function () {
    Route::get('dashboard', 'DashboardController@likedPosts')->name('dashboard');
    Route::get('profile', 'DashboardController@showProfile')->name('profile');
    Route::put('profile', 'DashboardController@updateProfile')->name('profile.update');
    Route::put('profile/password', 'DashboardController@changePassword')->name('profile.password');
    Route::get('comments', 'CommentController@index')->name('comment.index');
    Route::delete('/comment/{id}', 'CommentController@destroy')->name('comment.destroy');
    Route::get('/reply-comments', 'CommentReplyController@index')->name('reply-comment.index');
    Route::delete('/reply-comment/{id}', 'CommentReplyController@destroy')->name('reply-comment.destroy');
    Route::get('/user-liked-posts', 'DashboardController@likedPosts')->name('like.posts');
});


// View Composer
View::composer('layouts.frontend.partials.sidebar', function ($view) {
    $categories = Category::all()->take(10);
    $recentTags = Tag::all();
    $recentPosts = Post::latest()->take(3)->get();
    return $view->with('categories', $categories)->with('recentPosts', $recentPosts)->with('recentTags', $recentTags);
});


// Send Mail
Route::get('/send', function(){
    $post = Post::findOrFail(7);
    // Send Mail
    Mail::to('varanstudios@gmail.com')
        ->queue(new NewPost($post));

    return (new App\Mail\NewPost($post))->render();
});

resources/views/layouts/backend/partials/headermenu.blade.php
<header id="header" class="header">
    <div class="header-menu">
        <div class="col-sm-7">
            <a id="menuToggle" class="menutoggle pull-left"
                ><i class="fa fa fa-tasks"></i
            ></a>
            <div class="header-left">
                <a href="/">Home</a>
            </div>
        </div>

        <div class="col-sm-5">
            <div class="user-area dropdown float-right">
                <a
                    href="#"
                    class="dropdown-toggle"
                    data-toggle="dropdown"
                    aria-haspopup="true"
                    aria-expanded="false"
                >
                    <img
                        class="user-avatar rounded-circle"
                        src="{{asset('storage/user/'.Auth::user()->image)}}"
                        alt="User Avatar"
                    />
                </a>

                <div class="user-menu dropdown-menu">
                    @if (Auth::user()->role->id == 1)
                    <a class="nav-link" href="{{route('admin.profile')}}"
                        ><i class="fa fa-user"></i> My Profile</a
                    >
                    @elseif(Auth::user()->role->id == 2)
                    <a class="nav-link" href="{{route('user.profile')}}"
                        ><i class="fa fa-user"></i> My Profile</a
                    >
                    @else
                    null
                    @endif
                
                    <a class="nav-link" href="{{ route('logout') }}"
                        onclick="event.preventDefault();
                        document.getElementById('logout-form').submit();">
                        <i class="fa fa-power-off"></i> Logout
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </div>
            </div>
        </div>
    </div>
</header>

resources/views/layouts/backend/partials/navbar.blade.php
<aside id="left-panel" class="left-panel">
    <nav class="navbar navbar-expand-sm navbar-default">
        <div class="navbar-header">
            <button
                class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#main-menu"
                aria-controls="main-menu"
                aria-expanded="false"
                aria-label="Toggle navigation"
            >
                <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="./"
                ><img src="{{asset('backend/images/logo.png')}}" alt="Logo"
            /></a>
            <a class="navbar-brand hidden" href="./"
                ><img src="{{asset('backend/images/logo2.png')}}" alt="Logo"
            /></a>
        </div>

        <div id="main-menu" class="main-menu collapse navbar-collapse">
            @if (Auth::user()->role_id==1)
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{{route('admin.dashboard')}}">
                        <i class="menu-icon fa fa-dashboard"></i
                        >Dashboard
                    </a>
                </li>
                <h3 class="menu-title">CMS</h3>
                <!-- /.menu-title -->
                <li class="active">
                    <a href="{{route('admin.user.index')}}">
                        <i class="menu-icon fa fa-user"></i>Users
                    </a>
                </li>
                <li class="active">
                    <a href="{{route('admin.category.index')}}">
                        <i class="menu-icon fa fa-file"></i>Categories
                    </a>
                </li>
                <li class="active">
                    <a href="{{route('admin.post.index')}}">
                        <i class="menu-icon fa fa-file"></i>Posts
                    </a>
                </li>
                <li class="active">
                    <a href="{{route('admin.comment.index')}}">
                        <i class="menu-icon fa fa-file"></i>Comments
                    </a>
                </li>
                <li class="active">
                    <a href="{{route('admin.reply-comment.index')}}">
                        <i class="menu-icon fa fa-file"></i>Replied Comments
                    </a>
                </li>
            </ul>
            @else
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{{route('user.dashboard')}}">
                        <i class="menu-icon fa fa-dashboard"></i
                        >Dashboard
                    </a>
                </li>
                <h3 class="menu-title">CMS</h3>
                <!-- /.menu-title -->
                <li class="active">
                    <a href="{{route('user.comment.index')}}">
                        <i class="menu-icon fa fa-file"></i>Comments
                    </a>
                </li>
                <li class="active">
                    <a href="{{route('user.reply-comment.index')}}">
                        <i class="menu-icon fa fa-file"></i>Replied Comments
                    </a>
                </li>
            </ul>
            @endif
        </div>
        <!-- /.navbar-collapse -->
    </nav>
</aside>